version: "3.8"

services:
  app:
    image: polls_app
    build:
      context: .
    container_name: polls_django
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure:10
    depends_on:
      - "db"

  db:
    image: mysql:8.0.36
    container_name: polls_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Root2009
      - MYSQL_DATABASE=polls
    restart: on-failure:10
    volumes:
      - ./data/mysql/db:/var/lib/mysql
